In [1]:
import matplotlib.pyplot as plt
import math
import cmath
import numpy as np


In [2]:
#아이겐 벡터, 아이겐 벨류
#Sx
sz=np.array([[0,1],[1,0]])
ez=np.linalg.eig(sz)
ez


(array([ 1., -1.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [3]:
#Sy
sz=np.array([[0,-1j],[1j,0]])
ez=np.linalg.eig(sz)
ez

(array([ 1.+0.j, -1.+0.j]),
 array([[-0.        -0.70710678j,  0.70710678+0.j        ],
        [ 0.70710678+0.j        ,  0.        -0.70710678j]]))

In [4]:
#SZ
sz=np.array([[1,0],[0,-1]])
ez=np.linalg.eig(sz)
ez

(array([ 1., -1.]), array([[1., 0.],
        [0., 1.]]))

In [5]:
#Normal Modes
#행렬의 고유값은?
N = np.array([[2,-1],[-1,2]])
np.linalg.eig(N)


(array([3., 1.]), array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

In [ ]:
N행렬에 아이겐벡터를 곱하면N행렬과 아이겐 벨류 값이 나오는것이 아이겐 벡터,
아이겐 벨류이다. 아이겐 벨류와 아이겐 벡터는 물리적으로 의미를 얻는데
아이겐 벡터는 방향을 결정하고, 아이겐 벨류는 그 방향으로의 세기를 결정한다.


설명 -3