In [1]:
import random
import numpy as np

In [2]:
#차원의구 
#몬테카를로 방법을 이용한 3, 4, 5차원에서 $Cn의 근사값
#2차원
def s_circle(n):
    count=0
    for i in range(n):
        x,y=random.random(), random.random()
        if x*x+y*y<1:
            count+=1
    return 4*count/n
s_circle(100)

3.16

In [10]:
#3차원
def s_circle(n):
    count=0
    for i in range(n):
        x,y,z=random.random(), random.random(), random.random()
        if x*x+y*y+z*z<1:
            count+=1
    return 8*count/n
s_circle(100)

4.48

In [12]:
#4차원
def s_circle(n):
    count=0
    for i in range(n):
        x,y,z,w=random.random(), random.random(), random.random(), random.random()
        if x*x+y*y+z*z+w*w<1:
            count+=1
    return 16*count/n
s_circle(100)

4.96

In [13]:
def s_circle(n):
    count = 0
    for i in range(n):
        x,y,z,w,t = random.random(),random.random(),random.random(),random.random(),random.random()
        if x*x+y*y+z*z+w*w+t*t<1:
            count+=1
    return 32*count/n
s_circle(100)

4.8

In [6]:
#차원구의 면적근사값
def s_circle(n,t):
    count = 0
    for i in range(n):
        rr = np.zeros(t)
        m = 0
        while(m < t):
            x = random.random()
            rr[m] = x*x
            m+=1
        print(rr,sum(rr))
        if sum(rr)<1:
            count+=1
            
    return 2**t*count/n
s_circle(100,3)

[0.04037164 0.0514518  0.06159459] 0.1534180310525103
[0.00475719 0.00796691 0.00137712] 0.014101225277102128
[0.98754001 0.06729237 0.13233509] 1.1871674701152817
[0.29719093 0.06851145 0.00796525] 0.3736676355950996
[0.84154796 0.83809396 0.0240207 ] 1.7036626223471576
[0.58757652 0.73881468 0.38707212] 1.7134633187012764
[0.6877037  0.35378374 0.85874298] 1.9002304128161867
[0.71102287 0.70113577 0.13960202] 1.5517606625658789
[0.28149237 0.06562495 0.63840368] 0.9855210076827752
[0.05021061 0.01580656 0.79954204] 0.8655592105199383
[0.01616113 0.15076244 0.0031819 ] 0.17010546945546084
[0.2040813  0.68827915 0.90493543] 1.7972958752405597
[0.52352415 0.07914404 0.03959341] 0.6422615988561078
[0.02176137 0.51081621 0.08542992] 0.6180074947823792
[0.88797668 0.47884402 0.3377972 ] 1.704617900681463
[0.3508009  0.05503913 0.87749876] 1.283338789422719
[0.47545918 0.58137479 0.94381273] 2.0006467028687482
[0.8615011  0.12969515 0.51817859] 1.509374848710443
[0.12605734 0.3047302  0.474

4.4