In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

sx=np.array([[0,1],[1,0]])
ex=np.linalg.eig(sx)

sy=np.array([[0,complex(0,-1)],[complex(0,1),0]])
ey=np.linalg.eig(sy)

sz=np.array([[1,0],[0,-1]])
ez=np.linalg.eig(sz)

print("#1")
ex,ey,ez

#1


((array([ 1., -1.]), array([[ 0.70710678, -0.70710678],
         [ 0.70710678,  0.70710678]])),
 (array([ 1.+0.j, -1.+0.j]),
  array([[-0.        -0.70710678j,  0.70710678+0.j        ],
         [ 0.70710678+0.j        ,  0.        -0.70710678j]])),
 (array([ 1., -1.]), array([[1., 0.],
         [0., 1.]])))

In [2]:
M=np.array([[2,-1],[-1,2]])
np.linalg.eig(M) # 위쪽이 고유값, 아래쪽이 고유벡터

(array([3., 1.]), array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

In [3]:
print("#2")
print('아이겐밸류는 |M-lambda*E(단위행렬)|=0이 성립하게 만드는 lambda의 값이다.')
print('아이겐벡터는 각각의 lambda에 대응한 연립방정식 (M-lambda*E(단위행렬))X=0을 풀었을 때의 X이다.')
print("그리고 위에서 구한 고유벡터의 크기는 1이다.")

#2
아이겐밸류는 |M-lambda*E(단위행렬)|=0이 성립하게 만드는 lambda의 값이다.
아이겐벡터는 각각의 lambda에 대응한 연립방정식 (M-lambda*E(단위행렬))X=0을 풀었을 때의 X이다.
그리고 위에서 구한 고유벡터의 크기는 1이다.


In [4]:
print('lambda=1일 때 x1=-x2, lambda=3일 때 x1=x2')

lambda=1일 때 x1=-x2, lambda=3일 때 x1=x2


정반대의 말씀을 하고 계십니다. -3