# Pauli Matrices

파울리 행렬의 아이겐밸류와 아이겐벡터를 구하시오.

$$ s_x = \begin{pmatrix} 0 &amp; 1 \\ 1 &amp; 0 \end{pmatrix}, \quad
s_y = \begin{pmatrix} 0 &amp; -j \\ j &amp ; 0 \end{pmatrix}, \quad
s_z  = \begin{pmatrix} 1 &amp; 0 \\ 0 &amp ; -1 \end{pmatrix}. $$

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import math

In [2]:
s_x = np.array([[0,1],[1,0]])
es_x = np.linalg.eig(s_x)

es_x

(array([ 1., -1.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [3]:
a = 1j
s_y = np.array([[0,a],[-a,0]])
es_y = np.linalg.eig(s_y)

es_y

(array([ 1.+0.j, -1.+0.j]),
 array([[0.        +0.70710678j, 0.70710678+0.j        ],
        [0.70710678+0.j        , 0.        +0.70710678j]]))

In [4]:
s_z = np.array([[1,0],[0,-1]])
es_z = np.linalg.eig(s_z)

es_z

(array([ 1., -1.]), array([[1., 0.],
        [0., 1.]]))

# Normal Modes

(고전역학 by Thornton & Marion 챕터 12.2 및 예제 12.3 참조) 용수철 상수가 $k$인 용수철에 연결된 두 개의 물체의 노말 모드를 구해보자. 두 개의 물체의 운동방정식은 다음으로 주어진다.$$ -m w^2 x_1 = -2kx_1 +k x_2, \\
-m w^2 x_2 = k x_1 - 2 k x_2.$$eigenfrequencies $w$는 다음의 행렬식을 통해 구할 수 있다.$$ \frac{k}{m w^2} \begin{pmatrix} 2 &amp; -1 \\ -1 &amp; 2 \end{pmatrix} 
\begin{pmatrix} x_1 \\ x_2 \end{pmatrix}=
\lambda \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} $$

In [5]:
w = np.array([[2,-1],[-1,2]])
eigenvector_w = np.linalg.eig(w)

eigenvector_w

(array([3., 1.]), array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

따라서 eigenfrequencies는$$ w_1 = \sqrt{\frac{k}{m}}, \quad w_2 = \sqrt{\frac{3k}{m}}. $$

위에서 구한 아이겐벡터와 아이겐밸류의 의미를 설명하여라.

위에서 볼 수 있다시피 아이겐벡터의 값은 3과 1이 나오는 것을 볼 수 있다.
3일 때는 같은 크기지만 방향이 다름을 볼 수있고,
1일 때는 같은 크기에 같은 방향임을 볼 수 있다.
그러므로 아에겐벡터로 운동하는 물체의 크기와 방향을 알 수 있다.

설명 미흡 (-1.5)